id: d0e8f0c4f52046978c373c0e7ff5d57c
initial_creation_type: ocr
source_metadata:
  volumes:
    4bf0724815304263b436fadf05b60d46:
      base_file: v056.txt
      image_group_id: I1PD95902
      title: རྩོད་པ་བཟློག་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1605
      volume_number: 57
